{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPsxVUVw+G9OJdzdj1bOjvF",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/dimi-digi/techbasics1_dimitra_pantoula/blob/main/assignment2.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "yDjPgWU9la9T",
        "outputId": "eda40f5d-46d1-433f-e247-8bda4389f525"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Welcome to the Lord of the rings game!\n",
            "choose your character: Legolas\n",
            " You are in Mirkwood!                 [\\\n",
            "                  |\\)\n",
            "                  |\n",
            "                  Y\\\n",
            "                 T  \\\n",
            "                J    \\\n",
            "               Y/T`-._\\\n",
            "               /[|   ]|\n",
            "               | |    |\n",
            "   _\n",
            "  (,,)\n",
            "             /||.| /\\ |\n",
            "            /_|||| || |\n",
            "  L/\\       | \\| | '` |_ _ {|\n",
            " /v^v/\\/\\   `|  Y | [\n",
            "/ ,'./  \\.` |[   |\n",
            ",'     `    |\n",
            "--   -----.-(] [ |\n",
            "   Y Y  --;`~T   |\n",
            "  Y  YY   ;'~~l  |\n",
            " Y  Y Y   ;\\~~/\\{|\n",
            "     --   ;\\~~~\\/|\n",
            "    _    _; \\~~( Y``\n",
            "   (^)  (^)`._~ /\n",
            "    Y    Y    `'--..,-'\n",
            "      --           _\n",
            "          __   -  (^)  (^)\n",
            "      _\n",
            "\n",
            "You have just got back from hunting orcs around the castle all morning\n",
            "The sky looks strangely dark, the forest gives off sinister vibes and everyone has been warned off not to wander the forest alone\n",
            "choose the direction you are heading too:north\n",
            "You are in Hobbiton\n",
            "Bilbo is chilling outside smoking his pipe, creating different shapes and enjoying the sunny weather\n",
            "His birthday is coming up, but he is lately acting very mysterious\n",
            "choose an action:read\n",
            "You are reading a book under a tree\n",
            "Goodbye traveller!\n"
          ]
        }
      ],
      "source": [
        "import time\n",
        "\n",
        "location = \"start\"\n",
        "time.sleep(20)\n",
        "\n",
        "\n",
        "\n",
        "while True:\n",
        "  if location == \"start\":\n",
        "    print(\"Welcome to the Lord of the rings game!\")\n",
        "    character = str(input(\"choose your character: \"))\n",
        "\n",
        "  if character == \"Frodo\":\n",
        "    print(r\"\"\"you are starting in the Shire                                         __\n",
        "                 ,-_                  (`  ).\n",
        "                 |-_'-,              (     ).\n",
        "                 |-_'-'           _(        '`.\n",
        "        _        |-_'/        .=(`(      .     )\n",
        "       /;-,_     |-_'        (     (.__.:-`-_.'\n",
        "      /-.-;,-,___|'          `(       ) )\n",
        "     /;-;-;-;_;_/|\\_ _ _ _ _   ` __.:'   )\n",
        "        x_( __`|_P_|`-;-;-;,|        `--'\n",
        "        |\\ \\    _||   `-;-;-'\n",
        "        | \\`   -_|.      '-'\n",
        "        | /   /-_|_ `\n",
        "        |/   ,'-_|  \\\n",
        "        /____|'-_|___\\\n",
        " _..,____]__|_\\-_'|_|___,.._\n",
        "'                          ``'--,..,.\n",
        "\"\"\")\n",
        "    time.sleep(2)\n",
        "    print(r\"\"\"It is a beautiful sunny morning, birds are chirping and you can hear the sound of the water streaming down gently\n",
        "    .\n",
        "      \\ | /\n",
        "    '-.;;;.-'\n",
        "   -==;;;;;==-\n",
        "    .-';;;'-.\n",
        "      / | \\\n",
        "     '\n",
        "\"\"\")\n",
        "    time.sleep(2)\n",
        "    print(\"Everyone is working on their daily chores, but there is an uplifting atmosphere in the air\")\n",
        "\n",
        "  elif character == \"Legolas\":\n",
        "    print(r\"\"\" You are in Mirkwood!                 [\\\n",
        "                  |\\)\n",
        "                  |\n",
        "                  Y\\\n",
        "                 T  \\\n",
        "                J    \\\n",
        "               Y/T`-._\\\n",
        "               /[|   ]|\n",
        "               | |    |\n",
        "   _\n",
        "  (,,)\n",
        "             /||.| /\\ |\n",
        "            /_|||| || |\n",
        "  L/\\       | \\| | '` |_ _ {|\n",
        " /v^v/\\/\\   `|  Y | [\n",
        "/ ,'./  \\.` |[   |\n",
        ",'     `    |\n",
        "--   -----.-(] [ |\n",
        "   Y Y  --;`~T   |\n",
        "  Y  YY   ;'~~l  |\n",
        " Y  Y Y   ;\\~~/\\{|\n",
        "     --   ;\\~~~\\/|\n",
        "    _    _; \\~~( Y``\n",
        "   (^)  (^)`._~ /\n",
        "    Y    Y    `'--..,-'\n",
        "      --           _\n",
        "          __   -  (^)  (^)\n",
        "      _\n",
        "\"\"\")\n",
        "    time.sleep(2)\n",
        "    print(\"You have just got back from hunting orcs around the castle all morning\")\n",
        "    time.sleep(2)\n",
        "    print(\"The sky looks strangely dark, the forest gives off sinister vibes and everyone has been warned off not to wander the forest alone\")\n",
        "    time.sleep(2)\n",
        "\n",
        "  elif character == \"Gandalf\":\n",
        "    print(r\"\"\"You are in Minas Tirith\n",
        "                      / \\\\\\\n",
        "                      |n| |\n",
        "                    )(|_|-'X\n",
        "                   /  \\\\Y// \\\n",
        "                   |A | | |A|\n",
        "                   |  | | |_|\n",
        "            )(__X,,|__|MEB;;;-,)(,\n",
        "           /  \\\\\\;;;;;;;;;;;;/    \\\n",
        "           |A | |            | U  |\n",
        "         )_|  | |____)-----( |    |\n",
        "        ///|__|-'////       \\\\|___)=(__X\n",
        "       /////////////         \\\\///   \\/ \\\n",
        "       |           |  U    U |//     \\u|\n",
        "       |   )_,-,___|_)=(     | |  U  |_|_X\n",
        "       |  ///   \\\\|//   \\    | |  __ |/// \\\n",
        "     )_')(//     \\Y/     >---)=( /  \\\\|  | |-----------------..,\n",
        "    //// ,\\ u   u |   u /////   \\\\|  ||__|A|----------------..,, \\,\n",
        "   |  | .. |      |    ///// ,-, \\\\__||--------------------..,, \\, \\,\n",
        "---'--'_::_|______'----| u | | | |-----------------------..,, \\, \\, \\,\n",
        "                       |___|_|_|_|----------------------..,, \\, \\, \\ \\n                            `--------------------------..,, \\, \\, \\ \\\\\n",
        "                                                       \\, \\, \\, \\ \\ \\\n",
        "                                                         \\, \\, \\, \\ \\\\\n",
        "                                                           \\, \\, \\, \\ \\\n",
        "                                                             \\, \\, \\ \\\n",
        "                                                               \\, \\ \\\n",
        "                                                                 \\ \\\n",
        "                                                                  \\\n",
        "\"\"\")\n",
        "    time.sleep(2)\n",
        "    print(\"You rushed from Rohan to advise King Denethor to protect the city and raise an army against Sauron's dark forces\")\n",
        "    time.sleep(2)\n",
        "    print(\"The people of Minar Tirith have no suspected the threat yet and everyone is continuing their day as usual\")\n",
        "    location = \"direction1\"\n",
        "\n",
        "  direction1 = str(input(\"choose the direction you are heading too:\"))\n",
        "  if direction1 == \"north\":\n",
        "    print(\"You are in Hobbiton\")\n",
        "    time.sleep(2)\n",
        "    print(\"Bilbo is chilling outside smoking his pipe, creating different shapes and enjoying the sunny weather\")\n",
        "    time.sleep(2)\n",
        "    print(\"His birthday is coming up, but he is lately acting very mysterious\")\n",
        "    location = \"action\"\n",
        "  elif direction1 == \"south\":\n",
        "    print(\"You are Woodland Realm\")\n",
        "    time.sleep(2)\n",
        "    print(\"Thranduil, the King of the Silvan elves is sitting on his throne\")\n",
        "    time.sleep(2)\n",
        "    location = \"action\"\n",
        "  elif direction1 == \"east\":\n",
        "    print(\"You are in the fortress of Dol Guldur\")\n",
        "    time.sleep(2)\n",
        "    print(\"Sauron is gathering his forces there\")\n",
        "    time.sleep(2)\n",
        "    print(\"A war is brewing up. The skies have become darker and the air is poisoned.\")\n",
        "    location = \"action\"\n",
        "  elif direction1 == \"west\":\n",
        "    print(\"You are in a dungeon\")\n",
        "    time.sleep(2)\n",
        "    print(\"Gollum is near you. Be cautious and try not to make him mad\")\n",
        "  else:\n",
        "    print(\"invalid input\")\n",
        "\n",
        "  action = str(input(\"choose an action:\"))\n",
        "  if action == \"read\":\n",
        "    print(\"You are reading a book under a tree\")\n",
        "    time.sleep(2)\n",
        "    print(\"Goodbye traveller!\")\n",
        "    break\n",
        "  elif action == \"fight\":\n",
        "    print(\"You are fighting off some orcs with your sword\")\n",
        "    time.sleep(2)\n",
        "    print(\"Goodbye traveller!\")\n",
        "    break\n",
        "  elif action == \"go back\":\n",
        "    print(\"You are back in Hobbiton\")\n",
        "    time.sleep(2)\n",
        "    print(\"Goodbye traveller!\")\n",
        "  elif action == \"potion\":\n",
        "    print(\"You are helping Radagast the Brown to heal some animals in the forest\")\n",
        "    time.sleep(2)\n",
        "    print(\"Goodbye traveller!\")\n",
        "    break"
      ]
    }
  ]
}